"""Render the analysis results as Markdown."""

from __future__ import annotations

import json
from typing import Any

from clinqa.analysis.common import CheckResult
from clinqa.analysis.stats import ANSWER_TYPES

GENERATED_BANNER = (
    "> Generated by `make analyze` (`python -m clinqa.analyze --config configs/analysis.yaml`). "
    "Do not edit by hand; re-running produces identical output."
)


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    def cell(x: Any) -> str:
        return str(x).replace("|", "\\|").replace("\n", " ")

    out = ["| " + " | ".join(cell(h) for h in headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows]
    return "\n".join(out)


def _describe_row(d: dict[str, Any]) -> list[Any]:
    return [d.get(k, "") for k in ("n", "mean", "median", "min", "p5", "p95", "max")]


_DESC_HEADERS = ["n", "mean", "median", "min", "p5", "p95", "max"]


def _as_table(m: dict[str, Any]) -> str | None:
    """Render a dict of flat dicts as a table when the rows share most keys; transpose wide tables."""
    if len(m) < 2 or not all(isinstance(v, dict) and v for v in m.values()):
        return None
    if any(isinstance(x, (dict, list)) for v in m.values() for x in v.values()):
        return None
    keys: list[str] = []
    for v in m.values():
        keys.extend(k for k in v if k not in keys)
    if any(len(v) < len(keys) / 2 for v in m.values()):
        return None
    if len(keys) > 6 and len(keys) > len(m):
        return _table([""] + list(m), [[k] + [v.get(k, 0) for v in m.values()] for k in keys])
    return _table([""] + keys, [[k] + [v.get(kk, "") for kk in keys] for k, v in m.items()])


def render_metrics(m: Any, indent: int = 0) -> str:
    """Generic rendering of nested metric dicts: tables for comparable rows, bullets otherwise."""
    pad = "  " * indent
    if isinstance(m, dict):
        t = _as_table(m)
        if t is not None:
            return t
        lines = []
        for k, v in m.items():
            if isinstance(v, (dict, list)) and v:
                lines.append(f"{pad}- **{k}**:")
                sub = render_metrics(v, indent + 1)
                if sub.startswith("|"):
                    lines += ["", sub, ""]
                else:
                    lines.append(sub)
            else:
                lines.append(f"{pad}- **{k}**: {v if v not in ({}, []) else '(none)'}")
        return "\n".join(lines)
    if isinstance(m, list):
        if all(not isinstance(x, (dict, list)) for x in m):
            return "\n".join(f"{pad}- {x}" for x in m) if m else f"{pad}- (none)"
        return "\n".join(f"{pad}- {json.dumps(x, ensure_ascii=False)}" for x in m)
    return f"{pad}{m}"


def _render_table_md(table: dict[str, Any]) -> str:
    return _table(table["headers"], [[c if c != "" else "(empty)" for c in row] for row in table["rows"]])


def _render_example(title: str, r: dict[str, Any], split: str) -> str:
    parts = [f"### {title}", "", f"`{r['id']}` ({split}) - answer_type **{r['answer_type']}**", ""]
    parts += ["**Note**", "", "```text", r["note"], "```", "", f"**Table** (type `{r['table']['type']}`)", "",
              _render_table_md(r["table"]), "", f"**Question**: {r['question']}", "", f"**Gold answer**: {r['answer']}", ""]
    if r.get("tool_calls"):
        parts += ["**Gold tool_calls**:", "", "```json", json.dumps(r["tool_calls"], ensure_ascii=False, indent=2), "```", ""]
    return "\n".join(parts)


def _key_findings(stats: dict[str, Any], checks: list[CheckResult], splits: list[str]) -> list[str]:
    c = {x.check_id: x for x in checks}

    def by_split(check_id: str) -> str:
        cnt = c[check_id].counts_by_split(splits)
        return " / ".join(str(cnt[s]) for s in splits)

    q5, q6, q7, q8 = c["Q5"].metrics, c["Q6"].metrics, c["Q7"].metrics, c["Q8"].metrics
    n_bmi = stats["bmi_questions_by_type"]["tool_call"]
    q_only = sum(q5["bmi_args_only_in_question"].values())
    chained = q6["chained_bmi_minus_gold"]
    n_chained = sum(chained.values())
    off = n_chained - chained.get("+0.0", 0)
    uncertain_with_both = q8["bmi_decision_table"].get("uncertain | weight+height both present", 0)
    boundary = (
        "Apart from the ungrounded tool_call rows, 'both measurements available' separates tool_call from uncertain perfectly."
        if uncertain_with_both == 0
        else f"{uncertain_with_both} uncertain BMI examples have both measurements available."
    )
    findings = [
        f"**Ungrounded tool calls (Q5, error)**: {len(c['Q5'].flags)} of {n_bmi} calculate_bmi examples "
        f"({by_split('Q5')} train/val/test) have gold arguments whose weight and height appear nowhere in the note, "
        "table or question. Training on them teaches argument hallucination; see P-012.",
        f"**Measurements only in the question (Q5)**: {q_only} BMI examples state weight/height only in the question, "
        "not in the note - the model must read the question as part of the input.",
        "**BMI decision boundary (Q8)**: " + "; ".join(f"{k}: {v}" for k, v in q8["bmi_decision_table"].items())
        + f". {boundary}",
        f"**Imperial rounding (Q6)**: {q6['converted_args'].get('height:approx', 0)} inch heights do not round-trip to the gold cm value "
        f"(max gap {q6['max_abs_metric_diff']} cm); computing BMI from exactly converted values changes the result by "
        f"+/-0.1 in {off} of {n_chained} imperial examples. Evaluation uses source-precision-aware argument rules, not a universal tolerance (P-009).",
        f"**Stated BMIs are unreliable (Q7)**: {len(c['Q7'].flags)} of {q7['notes_with_stated_bmi_and_measurements']} notes that state a BMI "
        f"disagree with their own weight/height by > 0.5 (buckets: {q7['inconsistency_size_bmi_units']}).",
        f"**Arithmetic audit (Q10, heuristic)**: {len(c['Q10'].flags)} candidate issues across "
        f"{c['Q10'].metrics['equations_checked']} parsed equations and "
        f"{c['Q10'].metrics['by_amounts_checked']} 'by D' amounts; "
        f"{c['Q10'].metrics['by_amounts_verified']} 'by D' amounts verified. "
        "Flags require review; the checker does not establish the cause of a mismatch.",
        f"**External reference ranges (Q11)**: {len(c['Q11'].flags)} extractive answers cite a standard reference range that is not in "
        "their input (value comes from the note text, table is a different panel).",
        f"**Micro sign vs Greek mu (Q13)**: {len(c['Q13'].flags)} tool_call examples write µ (U+00B5) in question/answer but μ (U+03BC) "
        "in tool arguments.",
        f"**Overlap audit (Q3/Q18)**: Q3 flags={len(c['Q3'].flags)}, Q18 flags={len(c['Q18'].flags)}; "
        f"max observed test-vs-train Jaccard "
        f"{c['Q3'].metrics.get('max_jaccard_vs_train', {}).get('test', {}).get('max', '-')}. "
        "These checks do not prove absence of semantic or template leakage.",
        f"**Stretch B feasibility (Q19)**: {sum(c['Q19'].metrics['notes_with_covered_pair'].values())} notes contain a medication pair "
        f"covered by the reference; drug-pair keys are {c['Q19'].metrics['pair_order']} ordered, so lookup must be order-insensitive.",
    ]
    return findings


def render_report(
    stats: dict[str, Any],
    checks: list[CheckResult],
    examples: list[tuple[str, str, dict[str, Any]]],
    manifest: dict[str, Any],
    cfg: dict[str, Any],
) -> str:
    splits = stats["splits"]
    max_ex = cfg["report"]["max_examples_per_check"]
    L: list[str] = ["# Data Analysis and Quality Report", "", GENERATED_BANNER, ""]

    L += ["## Contents", "",
          "1. [Summary](#1-summary)", "2. [Splits and answer types](#2-splits-and-answer-types)",
          "3. [Text lengths](#3-text-lengths)", "4. [Structured tables](#4-structured-tables)",
          "5. [Tool calls](#5-tool-calls)", "6. [Answer-type deep dives](#6-answer-type-deep-dives)",
          "7. [Note structure](#7-note-structure)", "8. [Quality checks](#8-quality-checks)",
          "9. [Raw examples](#9-raw-examples)", "10. [Formatted examples](#10-formatted-examples)",
          "11. [Reproducibility](#11-reproducibility)", ""]

    # 1. Summary
    total = sum(stats["counts"].values())
    L += ["## 1. Summary", ""]
    L += [_table(["metric", "value"], [
        ["records (train / val / test)", " / ".join(str(stats["counts"][s]) for s in splits) + f" (total {total})"],
        ["reference entries", next((c.metrics.get("entries") for c in checks if c.check_id == "Q19"), "-")],
        ["mean note length, words (train)", stats["note_words"][splits[0]]["mean"]],
        ["examples with tool calls (train)", f"{stats['tool_calls'][splits[0]]['examples_with_tool_calls']} ({stats['tool_calls'][splits[0]]['pct_of_split']}%)"],
        ["labs / vitals tables (train)", f"{stats['table_type'][splits[0]]['labs']['n']} / {stats['table_type'][splits[0]]['vitals']['n']}"],
    ]), ""]
    L += ["**Key findings**", ""]
    L += [f"{i}. {x}" for i, x in enumerate(_key_findings(stats, checks, splits), start=1)] + [""]
    L += ["**Quality check overview** (status is the check's severity when it raises flags, otherwise `pass`):", ""]
    rows = []
    for c in checks:
        cnt = c.counts_by_split(splits + ["reference"])
        rows.append([c.check_id, c.title, c.status] + [cnt[s] for s in splits] + [cnt["reference"]])
    L += [_table(["id", "check", "status"] + splits + ["reference"], rows), ""]

    # 2. Splits
    L += ["## 2. Splits and answer types", ""]
    at_rows = []
    for s in splits:
        at = stats["answer_type"][s]
        at_rows.append([s, stats["counts"][s]] + [f"{at[t]['n']} ({at[t]['pct']}%)" for t in ANSWER_TYPES])
    at_rows.append(["spec (approx.)", "-"] + [f"~{stats['answer_type_spec'][t]}%" for t in ANSWER_TYPES])
    L += [_table(["split", "n"] + list(ANSWER_TYPES), at_rows), ""]
    L += ["The provided splits already have identical answer-type proportions (a stratified split). The formatter "
          "keeps every record, so the distribution is preserved by construction; Phase 2 asserts it.", ""]

    # 3. Lengths
    L += ["## 3. Text lengths", "", "**Note length (words, whitespace-delimited)**", ""]
    L += [_table(["split"] + _DESC_HEADERS, [[s] + _describe_row(stats["note_words"][s]) for s in splits]), ""]
    L += ["**Mean note length by answer type (words)**", ""]
    L += [_table(["split"] + list(ANSWER_TYPES), [[s] + [stats["note_words_by_type"][s][t].get("mean", "") for t in ANSWER_TYPES] for s in splits]), ""]
    L += ["**Question length (words)**", ""]
    L += [_table(["split"] + _DESC_HEADERS, [[s] + _describe_row(stats["question_words"][s]) for s in splits]), ""]
    L += ["**Gold answer length (words) by answer type, all splits**", ""]
    L += [_table(["answer_type"] + _DESC_HEADERS, [[t] + _describe_row(stats["answer_words_by_type"][t]) for t in ANSWER_TYPES]), ""]
    L += ["**Approximate token counts** (characters / 4; replaced by exact tokenizer counts in Phase 3)", ""]
    L += [_table(["segment"] + _DESC_HEADERS, [[k] + _describe_row(v) for k, v in stats["approx_tokens"].items()]), ""]
    L += ["Prompt = note + table + question. The system prompt and tool schemas add a fixed overhead on top.", ""]

    # 4. Tables
    L += ["## 4. Structured tables", "", "**Table type**", ""]
    L += [_table(["split", "labs", "vitals"], [[s] + [f"{stats['table_type'][s][k]['n']} ({stats['table_type'][s][k]['pct']}%)" for k in ("labs", "vitals")] for s in splits]), ""]
    panels = sorted({p for s in splits for p in stats["table_panel"][s]})
    L += ["**Panel** (inferred from row names; `mixed` / `vitals+body` are atypical tables, see Q14)", ""]
    L += [_table(["split"] + panels, [[s] + [stats["table_panel"][s].get(p, 0) for p in panels] for s in splits]), ""]
    L += ["**Answer type by panel (all splits)**", ""]
    L += [_table(["panel"] + list(ANSWER_TYPES), [[p] + [v[t] for t in ANSWER_TYPES] for p, v in stats["answer_type_by_panel"].items()]), ""]

    # 5. Tool calls
    L += ["## 5. Tool calls", ""]
    tc_rows = []
    for s in splits:
        t = stats["tool_calls"][s]
        tc_rows.append([s, f"{t['examples_with_tool_calls']} ({t['pct_of_split']}%)",
                        ", ".join(f"{k}: {v}" for k, v in t["by_tool"].items()),
                        ", ".join(f"{k} calls: {v}" for k, v in t["calls_per_example"].items())])
    L += [_table(["split", "examples with tool calls", "calls by tool", "calls per example"], tc_rows), ""]
    L += ["**unit_convert conversions used in gold calls**", ""]
    convs = sorted({k for s in splits for k in stats["tool_calls"][s]["unit_convert_conversions"]})
    L += [_table(["conversion"] + splits, [[c] + [stats["tool_calls"][s]["unit_convert_conversions"].get(c, 0) for s in splits] for c in convs]), ""]
    q5 = next(c for c in checks if c.check_id == "Q5")
    L += ["**Where calculate_bmi / unit_convert arguments come from** (gold-anchored reverse matching, see Q5)", ""]
    L += [render_metrics(q5.metrics["grounding_patterns"]), ""]
    L += ["**Weight/height units written in the note, by answer type (all splits)**", ""]
    L += [render_metrics(stats["body_measurement_units_in_note"]), ""]

    # 6. Deep dives
    L += ["## 6. Answer-type deep dives", "",
          "**uncertain: what the gold answer says is missing** (rule-based classification of the gold answer)", ""]
    cats = sorted({c for s in splits for c in stats["uncertain_category"][s]})
    L += [_table(["split"] + cats, [[s] + [stats["uncertain_category"][s].get(c, 0) for c in cats] for s in splits]), ""]
    L += ["**Questions mentioning BMI, by answer type**: " + ", ".join(f"{t}: {v}" for t, v in stats["bmi_questions_by_type"].items()), ""]
    L += ["**numeric_reasoning question operations** (multi-label, keyword-based)", ""]
    L += [render_metrics(stats["numeric_reasoning_categories"]), ""]
    L += ["**Question templates** (numbers masked as `#`)", ""]
    for t in ANSWER_TYPES:
        qt = stats["question_templates"][t]
        L += [f"*{t}*: {qt['n_distinct_templates']} distinct templates for {qt['n_examples']} questions", ""]
        L += [_table(["n", "template"], [[x["n"], x["template"]] for x in qt["top"]]), ""]

    # 7. Note structure
    L += ["## 7. Note structure", ""]
    L += [_table(["split", "plain", "markdown"], [[s, stats["note_style"][s].get("plain", 0), stats["note_style"][s].get("markdown", 0)] for s in splits]), ""]
    secs = list(stats["section_presence_pct"][splits[0]])
    L += ["**Section presence (% of notes with a `<Section>:` header)**", ""]
    L += [_table(["split"] + secs, [[s] + [stats["section_presence_pct"][s][k] for k in secs] for s in splits]), ""]
    st = sorted({k for s in splits for k in stats["allergy_status"][s]})
    L += ["**Allergy documentation**", ""]
    L += [_table(["split"] + st, [[s] + [stats["allergy_status"][s].get(k, 0) for k in st] for s in splits]), ""]
    L += ["**Other note characteristics**", ""]
    L += [_table(["split", "notes stating a BMI", "sex (F/M/unknown)", "age mean [min-max]", "medications per note (mean)"],
                 [[s, stats["inline_bmi_in_note"][s],
                   "/".join(str(stats["sex"][s].get(k, 0)) for k in ("F", "M", "unknown")),
                   f"{stats['age'][s].get('mean')} [{stats['age'][s].get('min')}-{stats['age'][s].get('max')}]",
                   stats["medications_per_note"][s].get("mean")] for s in splits]), ""]

    # 8. Checks
    L += ["## 8. Quality checks", "",
          "Severity when flagged: **error** = candidate schema/grounding failure requiring review; **warn** = likely "
          "issue affecting training or evaluation; **info** = dataset characteristic handled by design. "
          "All flags are in `reports/quality_flags.jsonl`.", ""]
    for c in checks:
        cnt = c.counts_by_split(splits + ["reference"])
        L += [f"### {c.check_id}. {c.title} - `{c.status}`", "", c.description, "",
              "**Flags**: " + ", ".join(f"{s}: {cnt[s]}" for s in splits + ["reference"] if s != "reference" or cnt[s]), "",
              f"**Handling**: {c.handling}", ""]
        if c.metrics:
            L += ["**Metrics**:", "", render_metrics(c.metrics), ""]
        for n in c.notes:
            L += [f"> {n}", ""]
        if c.flags:
            L += [f"**Examples** (first {min(max_ex, len(c.flags))} of {len(c.flags)}):", ""]
            L += [_table(["split", "id", "detail"], [[f.split, f.id, f.detail] for f in c.flags[:max_ex]]), ""]

    # 9. Examples
    L += ["## 9. Raw examples", "",
          "Raw records exactly as provided (one per answer type, plus imperial-unit and data-quality illustrations). "
          "The exact model input/output after formatting is added in section 10 once the chat format is fixed.", ""]
    for title, split, r in examples:
        L += [_render_example(title, r, split)]

    # 10. Formatted
    L += ["## 10. Formatted examples", "",
          "Exact model input/output after native Qwen chat rendering, generated by `make format`: "
          "[formatted_examples.md](formatted_examples.md). Supervised-token spans: [mask_audit.md](mask_audit.md).", ""]

    # 11. Repro
    L += ["## 11. Reproducibility", "", "```bash", "make data      # copies _data/* -> data/*.jsonl and writes data/MANIFEST.json",
          "make analyze   # writes reports/data_analysis.md, reports/data_stats.json, reports/quality_flags.jsonl", "```", "",
          "Input checksums (from `data/MANIFEST.json`):", ""]
    L += [_table(["file", "records", "sha256"], [[v["target"], v["n_records"], f"`{v['sha256']}`"] for v in manifest["files"].values()]), ""]
    L += ["Analysis configuration (`configs/analysis.yaml`):", "", "```json", json.dumps(cfg, indent=2, ensure_ascii=False), "```", ""]
    return "\n".join(L)
